stylelint/awesome-stylelint

README.md
When I checked the result of merging the previous PR on GitHub, I noticed that the markdown was broken.
This PR fixes broken markdown.
=> Fixed broken markdown.

README.md
This PR adds [stylelint-plugin-stylus](https://github.com/ota-meshi/stylelint-plugin-stylus).
=> Add stylelint-plugin-stylus

README.md
https://github.com/stylelint/awesome-stylelint/issues/20
=> Add stylelint-css-modules

README.md
Added tutorial for custom rules: https://medium.com/swlh/writing-your-first-custom-stylelint-rule-a9620bb2fb73
None, it's an addition to the tutorial section.
=> Added tutorial for custom rules

README.md
This PR adds [stylelint-no-restricted-syntax](https://github.com/niksy/stylelint-no-restricted-syntax) plugin.
=> Add stylelint-no-restricted-syntax plugin

README.md
This PR adds [stylelint-no-unresolved-module](https://github.com/niksy/stylelint-no-unresolved-module) plugin.
=> Add stylelint-no-unresolved-module plugin (#24)

README.md
Add [stylelint-max-lines](https://github.com/dkrnl/stylelint-max-lines) - Limit the count of a lines.
Add [stylelint-no-nested-media](https://github.com/dkrnl/stylelint-no-nested-media) - Disallow nested @media rules.
=> Add stylelint-max-lines & stylelint-no-nested-media

README.md
Closes https://github.com/stylelint/awesome-stylelint/issues/29.
=> Add stylelint-sass-render-errors plugin

README.md
Nothing much to say here, just read the brandnew README entry.
=> Introduce @isnotdefined/stylelint-plugin

README.md
None.
- Remove license section. See the [awesome guideline](https://github.com/sindresorhus/awesome/blob/1e92a1606b2bf6ea0bc57a07b6a74f4cb9ba0f2c/pull_request_template.md?plain=1#L86).
- Reduce link duplication by using a reference.
=> Fix lint problems

README.md
Ref: https://github.com/stylelint/stylelint/pull/5584
=> Use Stylelint (capital S)

README.md
None, as it's a plugin list update.
=> add stylelint-gamut to plugin list

README.md
Let me update the description of my stylelint-plugin.
=> Update description for @isnotdefined/stylelint-plugin

README.md
Ref https://github.com/stylelint/stylelint/pull/6573
Details over in that PR.
=> Add integrations and clean up

README.md
documentation addition.
– Added [stylelint-rem-over-px](https://github.com/a-tokyo/stylelint-rem-over-px) plugin
=> Add stylelint-rem-over-px

README.md
documentation addition.
Added [stylelint-file-max-lines](https://github.com/yixiaojiu/stylelint-file-max-lines) plugin
=> Add stylelint-file-max-lines

README.md
Repo moved from org to personal GitHub.
=> Fix stylelint-scales repo url

README.md
Adds the `stylelint-plugin-defensive-css` plugin to the Plugins list.
https://github.com/yuschick/stylelint-plugin-defensive-css
=> Adds Stylelint-Plugin-Defensive-CSS to Plugins List

README.md
None.
See https://www.npmjs.com/package/@isnotdefined/stylelint-plugin
=> Clarify name of `@isnotdefined/stylelint-plugin`

README.md
=> README.md: clarify stylelint-stylistic purpose

README.md
This PR adds [stylelint-config-recommended-vue](https://github.com/ota-meshi/stylelint-config-recommended-vue) to configs
=> Add stylelint-config-recommended-vue to configs

README.md
Based on a request to report the creation of a plugin [in the migration guide](https://stylelint.io/migration-guide/to-15/#:~:text=please%20let%20us%20know%20once%20you've%20published%20the%20plugin%20to%20npm%20so%20that%20we%20can%20add%20a%20link%20to%20it%20in%20this%20migration%20guide.)
=> Add stylelint-codeguide plugin

README.md
None, submit a new tool to provide stylelint config's types support.
=> add `stylelint-define-config`

README.md
[Reference](https://github.com/stylelint/stylelint/pull/7419).
=> Remove `stylelint-codeguide` and update `stylelint-stylistic`

README.md
I hope I've understood the [request](https://github.com/stylelint/awesome-stylelint/pull/62#issuecomment-1865303274) correctly.
=> Fix URLs for links to npm packages

README.md
=> Add stylistic config

README.md
Ref https://www.npmjs.com/package/stylelint-test-rule-node
=> Add stylelint-test-rule-node

README.md
None
No, it's self-explanatory
=> Add stylelint-formatter-gitlab-code-quality-report

README.md
=> Add stylelint-order related stuff

README.md
Ref https://www.npmjs.com/package/stylelint-formatter-pretty
=> Add stylelint-formatter-pretty

README.md
Ref https://www.npmjs.com/package/stylelint-actions-formatters
=> Add stylelint-actions-formatters

package.json
=> Add description and repository to package.json

README.md
=> Add stylelint-transform-function-no-whitespace

README.md
None, as it's just adding a new thing to the list
No, it's self-explanatory
=> Add stylelint-config-two-dash-bem

README.md
See: https://github.com/stylelint/stylelint/issues/8111#issuecomment-2457282951
=> Add `@csstools/stylelint-formatter-github`

README.md
Relates to #78
I ommited some entries for the issue to wait for community input
=> Removed unmaintained entries from #78 conservatively

README.md
#80
I could use input on the categories, this is merely a first draft. Even in this state though I find it substantially better than the status quo
=> Categorize plugins

README.md
Closes #83
Closes #78
Closes #82 - uses GitHub and Shopify as examples that enforce design systems
Closes #76 - picks out recess order as the most used logical ordering config
=> Document things that align with the awesome manifesto

README.md
See: https://github.com/stylelint/stylelint/issues/8391#issuecomment-2727206542
=> Add `stylelint-plugin-require-baseline`

.github/workflows/awesome-lint.yml
This fixes the code scanning alert:
- https://github.com/stylelint/awesome-stylelint/security/code-scanning/1
=> Specify safe permissions to CI workflow

.github/dependabot.yml
=> Set up Dependabot for GitHub Actions

.github/workflows/awesome-lint.yml
None.
Ref https://docs.github.com/en/actions/reference/security/secure-use#using-third-party-actions
=> Pin actions for security

README.md
Updated sugarss description for clarity.
Fixes awesomelint warning.
=> Document sugarss description
